### ISSUE TITLE
Handling (optional) dependencies for the ess submodules

### ISSUE THREAD

**Issue by nvaytet** [scipp/ess-legacy-v2#118]
In #115 we introduced `orsopy` as a soft dependency, because other techniques do not care about it.
The imaging module depends on `astropy`, but other modules don't care either.

Using soft dependencies is good so that we don't have too many dependencies in the base `ess`.
However, how do we make it easy for users to install all packages needed for e.g. reflectometry?
Do we have a different conda env file for each instrument? -> we will end up with many files that will go out of sync?

~~As a side note, probably a lot of packages are `pip` only, and are required to build the docs.
We should probably stop building the docs as part of `conda-build`.~~

**Comment by nvaytet** [comment]
The last part was done in #119

**Comment by SimonHeybrock** [comment]
Based on recent discussion, we should consider whether `scippneutron` may also be "optional". This could also allow for providing a PyPI package of `ess`.

**Comment by SimonHeybrock** [comment]
Obsolete, since we a splitting `ess`
