### ISSUE TITLE
Mask Bragg peaks in wavelength instead of TOF for sans2d workflow

### ISSUE THREAD

**Issue by nvaytet** [scipp/ess-legacy-v2#145]
In the SANS2d reduction workflow, we mask Bragg peaks while still in TOF:
https://github.com/scipp/ess/blob/main/docs/instruments/loki/sans2d_to_I_of_Q.ipynb?short_path=e46f518#L286-L293

The SANS2d detector is a relatively small flat panel, so masking in tof is an ok first approximation, if we are generous about the boundaries.
But technically, such features should be masked in wavelength, not tof.

**Comment by wpotrzebowski** [comment]
Ok, I agree tof boundary definition is rather historical than practical.  I guess there may be users that would still prefer thinking tof. Would it make sense to allow for both and set wavelength-based definition as a default?

**Comment by SimonHeybrock** [comment]
Wouldn't this be a bit challenging, as you need to know where the Bragg-peaks originate (I suppose it is not the sample) for being able to compute wavelength?

**Comment by SimonHeybrock** [comment]
It seems this is already implemented, see https://scipp.github.io/esssans/examples/sans2d.html#Define-reduction-parameters. Please reopen if this is not the case.
