### ISSUE TITLE
Reflectometry collimated and divergent mode

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess-legacy-v2#160]

**Comment by arm61** [comment]
The divergent mode is already satisfied with the [amor workflow](https://scipp.github.io/ess/instruments/amor/amor_reduction.html). Perhaps this should renamed as "Reflectometry collimated mode"?

**Comment by arm61** [comment]
There is [relevant Mantid documentation for the reflectometry reduction](https://docs.mantidproject.org/nightly/algorithms/ReflectometryReductionOne-v2.html#algm-reflectometryreductionone) (not including polarisation). However, I think that is might be easier to start from the Amor work and change the normalisation. I have some data from OFFSPEC that we can play with, @jl-wynen do you wanna book a pair programming afternoon?

**Comment by jl-wynen** [comment]
Done in #194
