### ISSUE TITLE
Update SANS workflow to discard normalization variances depending on threshold

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess-legacy-v2#162]
Result of discussion with Judith and @wpotrzebowski:

- Normalization terms in SANS almost always have very good statistics.
- We should update the SANS workflows to set `variances = None` in the relevant places.
  - Before this, add a check for `alpha`, defined as in our paper, and raise an error if a threshold is exceeded.
  - Exact threshold is to be defined, but we can start with something on the safe side and then iterate.
  - May consider issuing a warning if we get close to the threshold (but not above)?

**Comment by jl-wynen** [comment]
Should this be done explicitly in the notebook or automatically, e.g., by `loki.io.load_sans2d`?

**Comment by SimonHeybrock** [comment]
I would say it should be in the workflow, within the relevant function (not in the notebook). We may later want to switch to our improved approach, so building it into the loader is not ideal.
