### ISSUE TITLE
Update software-stack figure on front page?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess-legacy-v2#163]
Should we use this one instead?

![software-stack](https://user-images.githubusercontent.com/12912489/216256148-bc9b1036-4e42-4f3a-9202-9383795dd9e3.svg)

**Comment by nvaytet** [comment]
Don't think the external technologies is necessary? Also, I would say scippneutron makes use of plopp and scippnexus, so I would put those two on the same level, below scippneutron?

**Comment by SimonHeybrock** [comment]
Stacking things up correctly makes the figure unreadable.

**Comment by nvaytet** [comment]
> Stacking things up correctly makes the figure unreadable.

Why? Do you mean because `ess` may use `plopp` or `scippnexus` directly, without going via `scippneutron`?
