### ISSUE TITLE
Consider reverting #139 to use new ScippNexus features instead

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess-legacy-v2#164]
Title says it all. The `nexus` submodule added in #139 may be partially or fully obsolete. We should try using ScippNexus directly in one or two workflows and see what is missing.

**Comment by SimonHeybrock** [comment]
For context, when this was added we lacked a number of options we can rely on now:

- `scipp.DataGroup`.
- `sciline`
- `scippnexus` with new API.

**Comment by jl-wynen** [comment]
Switched to use `scippnexus.v1` for now in #206
