### ISSUE TITLE
WFM for scattering beamlines

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess-legacy-v2#165]
The current implementation assumes no scattering, i.e., is usable only for imaging. We need to support scattering from the sample, which will change the calculation of the neutron flight distance.

**Comment by nvaytet** [comment]
Do we also need to think about handling non-straight paths, e.g. in instruments with elliptical guides?

**Comment by SimonHeybrock** [comment]
Looking at FREIA, the WFM choppers are somewhere inside an elliptical section, so I am not sure how to properly compute distances...

**Comment by SimonHeybrock** [comment]
Handling the chopper side of things is proving too difficult for now (mainly due to lack of information and actual data). I will therefore focus on implementing the cutting/stitching component.

It should probably have the following inputs:

- Min and max time offsets (where to cut) for each subframe.
- Time shift to apply for each subframe.
- Position to use as the new "source", which could be used, e.g., to set a new L1, overriding the default source-sample distance calculation.
