### ISSUE TITLE
Replace chopper toolkit

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess-legacy-v2#166]
- Follow https://manual.nexusformat.org/classes/base_classes/NXdisk_chopper.html more closely, since ScippNexus can now load this quite well.
- Move to ScippNeutron, since this is generic.
- Propably use `scipp.DataGroup`.

**Comment by jl-wynen** [comment]
> Propably use scipp.DataGroup.

Doing this (and only this) right now because of the changes to dataset. However, in the long run, we should probably move to a dedicated data structure. We have fixed keys and item types, so we can be more explicit.
