### ISSUE TITLE
Masking tools

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess-legacy-v2#176]
This is required by DREAM and LOKI (and probably more):

In a notebook:

- Create plots that visualize counts for various logical/physical detector components, e.g., total counts in wires, modules, ...
- Provide Python function to detector broken components (such as wires), e.g., if they have no counts, or counts below a threshold.
- Plot the masks in the diagnostics plot. This lets the user verify the masks.
- All for manual (Python based) manipulation of the masks, e.g., be listing additional wires to mask by hand.
- Further plots may depend on the instrument, e.g., some may want to show the instrument view with masking in place.
- ~Masks will need to be saved to a file. Format to be decided.~ done, see #180.

Notebooks will likely be instrument-specific, since we need, e.g., different plots for different detector banks, and dimensionality depends on the instrument as well.

Potential example for DREAM:

![image](https://user-images.githubusercontent.com/12912489/232732148-0fc78178-5bef-443c-8e43-ca4536c7c901.png)

See also https://confluence.esss.lu.se/display/DAM/DREAM+-+Save+mask+to+file

**Comment by SimonHeybrock** [comment]
@nvaytet Is this done / replaced? If not, reopen please.

**Comment by nvaytet** [comment]
A tool for masking was added in https://github.com/scipp/scippneutron/pull/521.
General re-shaping and slicing of detectors will just be done with Scipp, as detectors are to be loaded with logical dimensions.
So yes, I would say it's done.
