### ISSUE TITLE
ESS copier template

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/ess-legacy-v2#200]
We are planning to make technique-specific or instrument-specific repositories instead of dumping everything into `scipp/ess`. The recently added https://github.com/scipp/copier_template will simplify a lot of the project setup. However, there will likely be ESS-specific project config (such as dependency, test setup, docs theming, ...) that we would not want to add to the generic `scipp/copier_template`.

According to the [copier docs](https://copier.readthedocs.io/en/stable/configuring/#applying-multiple-templates-to-the-same-subproject) is it possible to apply *multiple templates* to the same repository.

- Look into whether our ESS-projects needs are orthogonal to those from the generic `scipp/copier_template`.
- If so, setup such a template.

**Comment by jokasimr** [comment]
The ESS-specific project config is in progress [here](https://github.com/scipp/ess_reduction_copier_template/tree/main)

**Comment by SimonHeybrock** [comment]
Closing, since by now we have https://github.com/scipp/ess_template (albeit quite empty).
