### ISSUE TITLE
Reflectometry binning code should use `scipp` objects

### ISSUE THREAD

**Issue by arm61** [scipp/ess-legacy-v2#22]
Currently all of the binning code in `src/ess/reflectometry` and `src/ess/amor` uses NumPy arrays for binning of data. This is less optimal and more error prone as they lack units and dimensions. 

Once `scipp` has functions similar to `np.linspace` (https://github.com/scipp/scipp/issues/1865), everything should be converted to these `scipp` objects.

**Comment by nvaytet** [comment]
https://github.com/scipp/scipp/pull/1871 has now been merged

**Comment by arm61** [comment]
Hmmm...sounds like I have work to do 😬
