### ISSUE TITLE
Reflectometry docstrings should use same format as scipp python

### ISSUE THREAD

**Issue by arm61** [scipp/ess-legacy-v2#26]
Currently reflectometry docstrings use the Google style, but this is not the same as scipp python and causes issues with long lines. the reflectometry code should be changed to the same style as scipp and as a result 79 character line length can be imposed on all code (and therefore the flake8 excludes can be removed).

**Comment by arm61** [comment]
This is being achieved as a gradual process, #37 has some for the functions that have been changed.

**Comment by nvaytet** [comment]
Fixed by #61
