### ISSUE TITLE
Tests and docs for WFM code

### ISSUE THREAD

**Issue by nvaytet** [scipp/ess-legacy-v2#8]
#6 added code for stitching WFM data, but lacks documentation and tests.

**Comment by OwenArnold** [comment]
The lack of tests proved problematic around the time of the June 2021 ecosystem release. I had assumed everything was working correctly (all tests passed) and only found out later that the `ess-notebooks` were broken because of some migrations that needed to be made for WFM related code.

**Comment by nvaytet** [comment]
Fixed by #42 and #43
