### ISSUE TITLE
Do not import all modules in root

### ISSUE THREAD

**Issue by jl-wynen** [scipp/ess-legacy-v2#98]
Currently all modules (instruments, techniques) with actual implementations are imported in the top level `__init__.py`. This means that users are forced to import everything even when they only need code for a specific instrument. This slows down import and should probably be avoided.
But we have to balance this against users having to import too many things manually in every notebook.

**Comment by SimonHeybrock** [comment]
I suppose most users would only need a specific instrument and/or technique? So I'd say we want
```python
from ess import loki
from ess import sans
```
But `ess` should not import those?
